version: '3'
services:
  web:
    container_name: tracemap-api
    build: .
    ports:
     - '5000:5000'
     - '7687:7687'
     - '7474:7474'
     - '7473:7473'
    volumes:
     - .:/usr/src/app
    env_file: .env-dev
    network_mode: "host"